# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\pyqt_test.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


#from PyQt5 import QtCore, QtGui, QtWidgets

import requests
import xmltodict
import time
import threading
import sys
sys.path.append('.')
from pyqt_test import *

def CallApi():
    labelList = []
    labelList.append([ui.label_2, ui.label_3, ui.label_4, ui.label_5])
    labelList.append([ui.label_6, ui.label_7, ui.label_8, ui.label_9])
    labelList.append([ui.label_10, ui.label_11, ui.label_12, ui.label_13])
    labelList.append([ui.label_14, ui.label_15, ui.label_16, ui.label_17])
    labelList.append([ui.label_18, ui.label_19, ui.label_20, ui.label_21])
    
    key = 'thWTVZRkftwWDX%2F%2FBffYndD1kH0FA%2B9hrJ4tmX%2FTuFCKo00GOQ4qrPf0Qf5e0C83IRc5yPt%2F%2B6BM6X9n6P%2FSrQ%3D%3D'
    BusStopID = '8001378'
    while True:
        # response = requests.get('http://openapitraffic.daejeon.go.kr/api/rest/arrive/getArrInfoByStopID?serviceKey='+key+'&BusStopID='+BusStopID)    
        # dict_data_arrive = xmltodict.parse(response.text)
        # l = []
        # for i in dict_data_arrive['ServiceResult']['msgBody']['itemList']:
        #     response = requests.get('http://openapitraffic.daejeon.go.kr/api/rest/stationinfo/getStationByUid?serviceKey='+key+'&arsId='+i['LAST_STOP_ID'])    
        #     dict_data_stationinfo = xmltodict.parse(response.text)
        #     BusStopNm = ''
        #     if isinstance(dict_data_stationinfo['ServiceResult']['msgBody']['itemList'], dict):
        #         BusStopNm = dict_data_stationinfo['ServiceResult']['msgBody']['itemList']['BUSSTOP_NM']
        #     else:
        #         BusStopNm = dict_data_stationinfo['ServiceResult']['msgBody']['itemList'][0]['BUSSTOP_NM']
        #     l.append((i['ROUTE_NO'], i['DESTINATION'],i['EXTIME_MIN'], i['MSG_TP'], BusStopNm))
        # l.sort()
        l = []
        l.append(['104', '수통골', '6', '3', '한밭대학교'])
        l.append(['106', '비래동', '14', '3', '온천교'])
        l.append(['213', '대한통운종점', '3', '3', '서일여교'])
        l.append(['316', '대한통운', '5', '3', '디엔에프'])
        l.append(['617', '비래동', '10', '3', '크로바아파트'])
        for i in range(5):
            labelList[i][0].setText(l[i][0])
            labelList[i][1].setText(l[i][1])
            labelList[i][2].setText(l[i][2]+'분')
            labelList[i][3].setText(l[i][4])
            
        time.sleep(7)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    
    Dialog.setWindowFlags(QtCore.Qt.FramelessWindowHint)
    
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    
    thread = threading.Thread(target=CallApi)
    thread.daemon = True; thread.start()
    Dialog.showMaximized()
    sys.exit(app.exec_())
