# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\pyqt_test.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


#from PyQt5 import QtCore, QtGui, QtWidgets

import requests
import xmltodict
import time
import threading
import sys
import csv
from collections import defaultdict
sys.path.append('.')
from pyqt_test import *
from datetime import datetime

key = ''

def getInfo(filename):
    global key
    f = open(filename, 'r')
    lines = f.readlines()
    d = {}
    for line in lines:
        a,b = line.split('=')
        d[a] = b
    key = d['key']

def CallApi():
    global key
    labelList = []
    labelList.append([ui.label_2, ui.label_3, ui.label_4, ui.label_5])
    labelList.append([ui.label_6, ui.label_7, ui.label_8, ui.label_9])
    labelList.append([ui.label_10, ui.label_11, ui.label_12, ui.label_13])
    labelList.append([ui.label_14, ui.label_15, ui.label_16, ui.label_17])
    labelList.append([ui.label_18, ui.label_19, ui.label_20, ui.label_21])
    #weekDayList = ['월', '화', '수', '목', '금', '토', '일']
    
    BusStopID = '8001318'
    while True:
        now = datetime.now()
        ui.label_23.setText(str(now.month)+'월  '+str(now.day)+'일')
        ui.label_24.setText(str(now.hour)+':'+str(now.minute))
        
        response = requests.get('http://openapitraffic.daejeon.go.kr/api/rest/arrive/getArrInfoByStopID?serviceKey='+key+'&BusStopID='+BusStopID)    
        dict_data_arrive = xmltodict.parse(response.text)
        l = []
        for i in dict_data_arrive['ServiceResult']['msgBody']['itemList']:
            print(i)
            BusStopNm = ''
            if 'LAST_STOP_ID' in i.keys():
                response = requests.get('http://openapitraffic.daejeon.go.kr/api/rest/stationinfo/getStationByUid?serviceKey='+key+'&arsId='+i['LAST_STOP_ID'])    
                dict_data_stationinfo = xmltodict.parse(response.text)
                if isinstance(dict_data_stationinfo['ServiceResult']['msgBody']['itemList'], dict):
                    BusStopNm = dict_data_stationinfo['ServiceResult']['msgBody']['itemList']['BUSSTOP_NM']
                else:
                    BusStopNm = dict_data_stationinfo['ServiceResult']['msgBody']['itemList'][0]['BUSSTOP_NM']
            else:
                BusStopNm = '운행대기'
            l.append([i['ROUTE_NO'], i['DESTINATION'],i['EXTIME_MIN'], i['MSG_TP'], BusStopNm])
        l.sort()
        nowArriveList = []
        for i in range(5):
            if len(l[i][0]) == 1:
                l[i][0] = '마을'+l[i][0] 
            labelList[i][0].setText(l[i][0])
            labelList[i][1].setText(l[i][1])
            if l[i][3] == '07':
                labelList[i][2].setText('운행대기')
            elif l[i][3] == '06':
                labelList[i][2].setText('진입중')
                nowArriveList.append(l[i][0])
            else:
                labelList[i][2].setText(l[i][2]+'분')
            labelList[i][3].setText(l[i][4])
        nowArriveStr = ''
        for i in nowArriveList:
            nowArriveStr += i + '  '
        ui.label_22.setText(nowArriveStr)
        time.sleep(7)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    
    Dialog.setWindowFlags(QtCore.Qt.FramelessWindowHint)
    
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    getInfo("info.txt")
    thread = threading.Thread(target=CallApi)
    thread.daemon = True; thread.start()
    Dialog.showMaximized()
    sys.exit(app.exec_())
