# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\pyqt_test.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1080, 1920)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(0, 0, 1081, 1921))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("BackgraoundImage.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
#import resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    
    Dialog.setWindowFlags(QtCore.Qt.FramelessWindowHint)
    
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.showMaximized()
    
    sys.exit(app.exec_())
